grails-app/domain/hitstore/Order.groovy
package hitstore

import org.bson.types.ObjectId

class Order {

    ObjectId id
    String name
    String adress
    String chartId
    String status
    Double total
    String paymentType
    String deliverOption
    String clientId
    Map<String, Integer> productList = new HashMap<>()
    Date createdDate = new Date()

    static embedded = ['productList']

    static constraints = {
        name nullable: true
        adress nullable: true
        status nullable: true
        total nullable: true
        paymentType nullable: true
        deliverOption nullable: true
        clientId nullable: true
    }
}

grails-app/views/layouts/_header.gsp
<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/#">
                <asset:image src="hitLogo.jpg" alt="Hit Logo" class="logo"/>
            </a>
        </div>
        <div class="navbar-collapse collapse" aria-expanded="false" style="height: 0.8px;">
            <ul class="nav navbar-nav navbar-right menu">
                <g:pageProperty name="page.nav" />
                <li>
                    <a href="/#">Home</a>
                </li>
                <li>
                    <a href="${g.createLink(action: 'index' , controller: 'catalogo')}">Catalogo</a>
                </li>
                <sec:ifLoggedIn>
                    <sec:ifAllGranted roles="ROLE_ADMIN">
                        <li>
                            <a href="${g.createLink(action: 'index', controller: 'product')}">Gerenciamento de produtos</a>
                        </li>
                        <li>
                            <a href="${g.createLink(action: 'index' , controller: 'order')}">Histórico de pedidos</a>
                        </li>
                        <li>
                            <a href="/logout">Logout</a>
                        </li>
                    </sec:ifAllGranted>
                    <sec:ifAllGranted roles="ROLE_USER">
                        <li>
                            <a href="${g.createLink(action: 'index' , controller: 'chart')}">Carrinho</a>
                        </li>
                        <li>
                            <a href="${g.createLink(action: 'orderList' , controller: 'user')}">Pedidos</a>
                        </li>
                        <li class="loginName">
                            Bem vindo, <sec:username/>!
                        </li>
                        <li>
                            <a href="/logout">Logout</a>
                        </li>
                    </sec:ifAllGranted>
                </sec:ifLoggedIn>
                <sec:ifNotLoggedIn>
                    <li>
                        <a href="/login">Login</a>
                    </li>
                    <li>
                        <a href="${g.createLink(action: 'index' , controller: 'user')}">Cadastre-se</a>
                    </li>
                </sec:ifNotLoggedIn>
            </ul>
        </div>
    </div>
</div>

grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

    <g:render template="/layouts/header" />

    <g:layoutBody/>

    <div class="footer" role="contentinfo"></div>

    <div id="spinner" class="spinner" style="display:none;">
        <g:message code="spinner.alt" default="Loading&hellip;"/>
    </div>

    <asset:javascript src="application.js"/>

</body>
</html>